### ISSUE TITLE
Exceptions are being swallowed

### ISSUE THREAD

**Issue by trevorhreed** [uniibu/koa-nunjucks-async#6]
Exceptions are being swallowed in the `render` and `renderString` context functions (see below). I think either the `try-catch` statements should be removed so developers can catch the exception themselves and handle it however they like.

https://github.com/uniibu/koa-nunjucks-async/blob/a405714cdd3412d3e4f9673bbe29fab336b5b699/src/index.js#L76-L85

https://github.com/uniibu/koa-nunjucks-async/blob/a405714cdd3412d3e4f9673bbe29fab336b5b699/src/index.js#L88-L94

**Comment by uniibu** [comment]
Fixed at `v1.1.0`
